name: ESLint Code Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Use a Node.js version compatible with your project
    - name: Install Dependencies
      run: npm install
    - name: Create Reports Directory
      run: mkdir -p reports # Add this step to explicitly create the directory
    - name: Run ESLint
      run: npx eslint --format=@microsoft/eslint-formatter-sarif --output-file=reports/eslint-results.sarif .
      continue-on-error: true
    - name: Upload SARIF report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: reports/eslint-results.sarif